### ISSUE TITLE
Missing md5sum dependency

### ISSUE THREAD

**Issue by turbaszek** [PolideaInternal/airflow-breeze#24]
On MacOS I had an `md5sum: command not found` error, so I would suggest adding an information about this dependency to `README.prerequisites.md`. 

Running `brew install md5sha1sum` solved the problem.

**Comment by potiuk** [comment]
Maybe you can make a PR with it :)?

**Comment by sprzedwojski** [comment]
I've also ran into this issue before, which I described here: https://github.com/GoogleCloudPlatform/oozie-to-airflow/pull/105#issuecomment-484911458
What helped me was upgrading `coreutils` on MacOS to 8.31.
